FROM aerokube/selenoid
VOLUME - "/c/Projects/selenoid-docker/selenoid/config/:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/c/Projects/selenoid-docker/selenoid/video:/opt/selenoid/video"
      - "/c/Projects/selenoid-docker/selenoid/logs:/opt/selenoid/logs"
EXPOSE
